services:
  - type: web
    name: streamvibe-backend
    env: python
    buildCommand: ./render-build.sh
    startCommand: startCommand: gunicorn Capstone.wsgi:application --bind 0.0.0.0:$PORT

    rootDir: .
    envVars:
      - key: DJANGO_DEBUG
        value: False
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://svibe.netlify.app, https://streamvibe-backend-q0e9.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://svibe.netlify.app, https://streamvibe-backend-q0e9.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: streamvibe-db
          property: connectionString

databases:
  - name: streamvibe-db
    databaseName: streamvibe
    user: streamvibe
    plan: free
