# Generated by Django 5.2 on 2025-04-06 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_populate_movie_fields'),
        ('reviews', '0004_alter_review_unique_together_alter_review_movie_id_and_more'),
    ]

    operations = [
    ]
