# Generated by Django 5.2 on 2025-04-06 15:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_review_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='review',
            name='movie_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'movie_title')},
        ),
    ]
